# Generated by Django 6.0.6 on 2026-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create_at')),
                ('modifield_at', models.DateField(auto_now=True, verbose_name='Modifield_at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('doc_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=20, verbose_name='doc_type')),
                ('doc_number', models.CharField(max_length=20, unique=True, verbose_name='doc_number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
