# Generated by Django 6.0.6 on 2026-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create_at')),
                ('modifield_at', models.DateField(auto_now=True, verbose_name='Modifield_at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('sku', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='SKU')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
